create table if not exists public.tahsin_users (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint unique not null,
  telegram_username text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recitations (
  id uuid primary key default gen_random_uuid(),
  user_id bigint references public.tahsin_users(id) on delete set null,
  surah smallint not null check (surah between 1 and 114),
  ayah smallint not null check (ayah > 0),
  transcription text,
  expected_text text not null,
  accuracy_pct numeric(5,2) check (accuracy_pct between 0 and 100),
  asr_model text,
  analysis_version text not null default 'm1-word-level',
  status text not null default 'completed'
    check (status in ('received','processing','completed','failed','needs_review')),
  created_at timestamptz not null default now()
);

create table if not exists public.recitation_words (
  id bigint generated by default as identity primary key,
  recitation_id uuid not null references public.recitations(id) on delete cascade,
  position integer not null check (position >= 0),
  expected text,
  heard text,
  status text not null
    check (status in ('correct','incorrect','missed','extra')),
  created_at timestamptz not null default now()
);

create index if not exists recitations_user_created_idx
  on public.recitations (user_id, created_at desc);

create index if not exists recitation_words_recitation_position_idx
  on public.recitation_words (recitation_id, position);

alter table public.tahsin_users enable row level security;
alter table public.recitations enable row level security;
alter table public.recitation_words enable row level security;

revoke all on table public.tahsin_users from anon, authenticated;
revoke all on table public.recitations from anon, authenticated;
revoke all on table public.recitation_words from anon, authenticated;

grant select, insert, update, delete on table public.tahsin_users to service_role;
grant select, insert, update, delete on table public.recitations to service_role;
grant select, insert, update, delete on table public.recitation_words to service_role;

grant usage, select on sequence public.tahsin_users_id_seq to service_role;
grant usage, select on sequence public.recitation_words_id_seq to service_role;


create table if not exists public.benchmark_cases (
  id uuid primary key default gen_random_uuid(),
  case_key text unique not null,
  surah smallint not null check (surah between 1 and 114),
  ayah smallint not null check (ayah > 0),
  category text not null,
  audio_path text,
  teacher_transcription text,
  teacher_notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.benchmark_labels (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.benchmark_cases(id) on delete cascade,
  error_type text not null,
  expected_value text,
  observed_value text,
  rule_id text,
  start_ms integer check (start_ms is null or start_ms >= 0),
  end_ms integer check (end_ms is null or end_ms >= 0),
  severity text,
  teacher_note text,
  created_at timestamptz not null default now(),
  check (end_ms is null or start_ms is null or end_ms >= start_ms)
);

create table if not exists public.benchmark_runs (
  id uuid primary key default gen_random_uuid(),
  git_sha text,
  model_version text,
  evidence_level text not null default 'teacher-audio',
  metrics jsonb not null default '{}'::jsonb,
  passed boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.benchmark_results (
  id bigint generated by default as identity primary key,
  run_id uuid not null references public.benchmark_runs(id) on delete cascade,
  case_id uuid not null references public.benchmark_cases(id) on delete cascade,
  case_passed boolean not null default false,
  metrics jsonb not null default '{}'::jsonb,
  output jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (run_id, case_id)
);

create index if not exists benchmark_labels_case_idx
  on public.benchmark_labels (case_id);
create index if not exists benchmark_results_run_idx
  on public.benchmark_results (run_id);
create index if not exists benchmark_results_case_idx
  on public.benchmark_results (case_id);

alter table public.benchmark_cases enable row level security;
alter table public.benchmark_labels enable row level security;
alter table public.benchmark_runs enable row level security;
alter table public.benchmark_results enable row level security;

revoke all on table public.benchmark_cases from anon, authenticated;
revoke all on table public.benchmark_labels from anon, authenticated;
revoke all on table public.benchmark_runs from anon, authenticated;
revoke all on table public.benchmark_results from anon, authenticated;

grant select, insert, update, delete on table public.benchmark_cases to service_role;
grant select, insert, update, delete on table public.benchmark_labels to service_role;
grant select, insert, update, delete on table public.benchmark_runs to service_role;
grant select, insert, update, delete on table public.benchmark_results to service_role;

grant usage, select on sequence public.benchmark_labels_id_seq to service_role;
grant usage, select on sequence public.benchmark_results_id_seq to service_role;
