create table if not exists public.tahsin_users (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint unique not null,
  telegram_username text,
  display_name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recitations (
  id uuid primary key default gen_random_uuid(),
  user_id bigint references public.tahsin_users(id) on delete set null,
  surah smallint not null check (surah between 1 and 114),
  ayah smallint not null check (ayah > 0),
  transcription text,
  expected_text text not null,
  accuracy_pct numeric(5,2) check (accuracy_pct between 0 and 100),
  asr_model text,
  analysis_version text not null default 'm1-word-level',
  status text not null default 'completed'
    check (status in ('received','processing','completed','failed','needs_review')),
  created_at timestamptz not null default now()
);

create table if not exists public.recitation_words (
  id bigint generated by default as identity primary key,
  recitation_id uuid not null references public.recitations(id) on delete cascade,
  position integer not null check (position >= 0),
  expected text,
  heard text,
  status text not null
    check (status in ('correct','incorrect','missed','extra')),
  created_at timestamptz not null default now()
);

create index if not exists recitations_user_created_idx
  on public.recitations (user_id, created_at desc);

create index if not exists recitation_words_recitation_position_idx
  on public.recitation_words (recitation_id, position);

alter table public.tahsin_users enable row level security;
alter table public.recitations enable row level security;
alter table public.recitation_words enable row level security;

revoke all on table public.tahsin_users from anon, authenticated;
revoke all on table public.recitations from anon, authenticated;
revoke all on table public.recitation_words from anon, authenticated;

grant select, insert, update, delete on table public.tahsin_users to service_role;
grant select, insert, update, delete on table public.recitations to service_role;
grant select, insert, update, delete on table public.recitation_words to service_role;

grant usage, select on sequence public.tahsin_users_id_seq to service_role;
grant usage, select on sequence public.recitation_words_id_seq to service_role;
